export const CART_PRODUCTS_REQUEST = "CART_PRODUCTS_REQUEST"
export const CART_PRODUCTS_SUCCESS = "CART_PRODUCTS_SUCCESS"
export const CART_PRODUCTS_FAILURE = "CART_PRODUCTS_FAILURE"

export const UPDATED_CART_REQUEST = "UPDATED_CART_REQUEST"
export const UPDATED_CART_SUCCESS = "UPDATED_CART_SUCCESS"
export const UPDATED_CART_FAILURE = "UPDATED_CART_FAILURE"